// function movething() {
//     document.getElementById("movable").style.animation = "mynewmove .5s 1";
// }
$(document).ready(function(){
    var count = 1;
    $("#p2").hide();
    $("#p3").hide();
    $("#p4").hide();
    $("#p5").hide();
    $("#p6").hide();
    $("#p7").hide();
    $("#p8").hide();
    $("#rightarrow").click(function(){
        if(count == 1)
        {
            $("#p1").fadeOut();
            $("#p2").fadeIn();
            count++;
        }
        else if (count == 2)
        {
            $("#p2").fadeOut();
            $("#p3").fadeIn();
            count++;
        }
        else if (count == 3)
        {
            $("#p3").fadeOut();
            $("#p4").fadeIn();
            count++;
        }
        else if (count == 4)
        {
            $("#p4").fadeOut();
            $("#p5").fadeIn();
            count++;
        }
        else if (count == 5)
        {
            $("#p5").fadeOut();
            $("#p6").fadeIn();
            count++;
        }
        else if (count == 6)
        {
            $("#p6").fadeOut();
            $("#p7").fadeIn();
            count++;
        }
        else if (count == 7)
        {
            $("#p7").fadeOut();
            $("#p8").fadeIn();
            count++;
        }
        else if (count == 8)
        {
            $("#p8").fadeOut();
            $("#p1").fadeIn();
            count = 1;
        }
    });
    $("#leftarrow").click(function(){
        if(count == 1)
        {
            $("#p1").fadeOut();
            $("#p8").fadeIn();
            count = 8;
        }
        else if (count == 2)
        {
            $("#p2").fadeOut();
            $("#p1").fadeIn();
            count--;
        }
        else if (count == 3)
        {
            $("#p3").fadeOut();
            $("#p2").fadeIn();
            count--;
        }
        else if (count == 4)
        {
            $("#p4").fadeOut();
            $("#p3").fadeIn();
            count--;
        }
        else if (count == 5)
        {
            $("#p5").fadeOut();
            $("#p4").fadeIn();
            count--;
        }
        else if (count == 6)
        {
            $("#p6").fadeOut();
            $("#p5").fadeIn();
            count--;
        }
        else if (count == 7)
        {
            $("#p7").fadeOut();
            $("#p6").fadeIn();
            count--;
        }
        else if (count == 8)
        {
            $("#p8").fadeOut();
            $("#p7").fadeIn();
            count--;
        }

    });

    $("#parent").hide();
    $("#parent2").hide();
    $("#toTop").click(function(){
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div26").hide();
        $("#div31").hide();
        $("#div32").hide();
    });
    $("#toTop33").click(function(){
        $("#div33").hide();
    });
    $("#Button1").click(function(){
        $("#parent1").show();
        $("#div1").show();
        $("#div2").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div31").hide();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button2").click(function(){
        $("#parent1").show();
        $("#div2").show();
    	$("#div1").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div31").hide();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button3").click(function(){
        $("#parent1").show();
        $("#div3").show();
        $("#div1").hide();
        $("#div2").hide();
        $("#div4").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div31").hide();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button4").click(function(){
        $("#parent1").show();
        $("#div4").show();
        $("#div1").hide();
        $("#div2").hide();
        $("#div3").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div31").hide();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button5").click(function(){
        $("#parent1").show();
        $("#div5").show();
        $("#div1").hide();
        $("#div2").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div31").hide();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button11").click(function(){
        $("#parent2").show();
        $("#div11").show();
        $("#div12").hide();
        $("#div13").hide();
        $("#div14").hide();
    });
    $("#Button12").click(function(){
        $("#parent2").show();
        $("#div12").show();
        $("#div11").hide();
        $("#div13").hide();
        $("#div14").hide();
    });
    $("#Button13").click(function(){
        $("#parent2").show();
        $("#div13").show();
        $("#div11").hide();
        $("#div12").hide();
        $("#div14").hide();
    });
    $("#Button14").click(function(){
        $("#parent2").show();
        $("#div14").show();
        $("#div11").hide();
        $("#div12").hide();
        $("#div13").hide();
    });
    $("#Button21").click(function(){
        $("#parent2").show();
        $("#div21").show();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div26").hide();
    });
    $("#Button22").click(function(){
        $("#parent2").show();
        $("#div22").show();
        $("#div21").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div26").hide();
    });
    $("#Button23").click(function(){
        $("#parent2").show();
        $("#div23").show();
        $("#div21").hide();
        $("#div22").hide();
        $("#div24").hide();
        $("#div25").hide();
        $("#div26").hide();
    });
    $("#Button24").click(function(){
        $("#parent2").show();
        $("#div24").show();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div25").hide();
        $("#div26").hide();
    });
    $("#Button25").click(function(){
        $("#parent2").show();
        $("#div25").show();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div26").hide();
    });
    $("#Button26").click(function(){
        $("#parent2").show();
        $("#div26").show();
        $("#div21").hide();
        $("#div22").hide();
        $("#div23").hide();
        $("#div24").hide();
        $("#div25").hide();
    });
    $("#Button31").click(function(){
        $("#parent2").show();
        $("#div31").show();
        $("#div32").hide();
        $("#div33").hide();
    });
    $("#Button32").click(function(){
        $("#parent2").show();
        $("#div32").show();
        $("#div31").hide();
        $("#div33").hide();
    });
    $("#Button33").click(function(){
        $("#parent2").show();
        $("#div33").show();
        $("#div31").hide();
        $("#div32").hide();
    });
});
