// function movething() {
//     document.getElementById("movable").style.animation = "mynewmove .5s 1";
// }
$(document).ready(function(){
	$("#div1").hide();
	$("#div2").hide();
    $("#div3").hide();
    $("#div4").hide();
    $("#div5").hide();
    $("#div11").hide();
    $("#div21").hide();
    $("#parent").hide();
    $("#parent2").hide();
    $("#p2").hide();
    $("#rightarrow").click(function(){
        $("#p1").fadeOut();
        $("#p2").fadeIn();
    });
    $("#toTop11").click(function(){
        $("#div11").hide();
    });
    $("#toTop12").click(function(){
        $("#div12").hide();
    });
    $("#toTop21").click(function(){
        $("#div21").hide();
    });
    $("#Button1").click(function(){
        $("#parent1").show();
        $("#div1").fadeToggle();
        $("#div2").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div21").hide();
    });
    $("#Button2").click(function(){
        $("#parent1").show();
        $("#div2").fadeToggle();
    	$("#div1").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div21").hide();
    });
    $("#Button4").click(function(){
        $("#parent1").show();
        $("#div4").fadeToggle();
        $("#div1").hide();
        $("#div2").hide();
        $("#div3").hide();
        $("#div5").hide();
        $("#div11").hide();
        $("#div21").hide();
    });
    $("#Button5").click(function(){
        $("#parent1").show();
        $("#div5").fadeToggle();
        $("#div1").hide();
        $("#div2").hide();
        $("#div3").hide();
        $("#div4").hide();
        $("#div11").hide();
        $("#div21").hide();
    });
    $("#Button11").click(function(){
        $("#parent2").show();
        $("#div11").fadeToggle();
        $("#div12").hide();
        $("#div21").hide();
    });
    $("#Button12").click(function(){
        $("#parent2").show();
        $("#div12").fadeToggle();
        $("#div11").hide();
        $("#div21").hide();
    });
    $("#Button21").click(function(){
        $("#parent2").show();
        $("#div21").fadeToggle();
        $("#div12").hide();
        $("#div11").hide();
    });
});
